name: Bug Report
description: |
  File a bug report to be fixed.

  Sponsors get priority issues, PRs, fixes and requests. Not a sponsor? [You're a just click away!](https://github.com/sponsors/DarkGhostHunter).
title: "[X.x] What does happen that is considered an error or bug?"
labels: ["bug"]
assignees:
  - DarkGhostHunter
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        The more detailed this bug report is, the faster it can be reviewed and fixed.
  - type: input
    id: version-bundler-platform
    attributes:
      label: Bundler & Interpreter
      description: Exact Bundler name and Interpreter versions, if applicable.
      placeholder: Vite 5.1.6 - Node.js 20.11.1
    validations:
      required: false
  - type: input
    id: version-browser-os
    attributes:
      label: Browser & OS
      description: Exact Browser version and OS (platform) running this package.
      placeholder: Safari 12 (14606.1.36) - macOS 14.1
    validations:
      required: false
  - type: checkboxes
    id: requirements
    attributes:
      label: Have you done this?
      options:
        - label: I have checked my logs and I am sure is a bug in this package.
          required: true
        - label: I can reproduce this bug in isolation (vanilla install)
          required: true
        - label: I can suggest a workaround as a Pull Request
          required: false
  - type: textarea
    id: expectation
    attributes:
      label: Expectation
      description: Write what you expect to (correctly) happen.
      placeholder: When I do this, I expect to happen that.
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Write what (incorrectly) happens instead.
      placeholder: Instead, when I do this, I receive that.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: Paste the code to assert in Vitest, or just comment with the repository with the bug to reproduce.
      render: javascript
      placeholder: |
        import laragear from 'laragear'
        
        const test = laragear.make().break()

        expect(test).toBe(false);

        // or comment with "https://github.com/my-name/my-bug-report"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Stack trace & logs
      description: If you have a **full** console stack trace, you can copy it here. You may hide sensible information.
      placeholder: This is automatically formatted into code, no need for ``` backticks.
      render: shell
    validations:
      required: false
